#! /bin/bash

# Creates a release-independent tar file containing a basic home
# directory for the user, which is installed by bootstrap.sh.

. setup/config

TMPDIR=$(mktemp -d -t vagrantXXXXXX) || exit 1
echo "using temporary directory $TMPDIR"
(
    cd $TMPDIR

    # Set up ssh configuration.
    mkdir -m 700 .ssh
    cat $HOME/.ssh/id*.pub >.ssh/authorized_keys

    # Set up git configuration.  Copy $HOME/.gitconfig, and any
    # external files referenced in .gitconfig, into the new homedir.
    USERNAME="$USERNAME" \
    perl -p \
         -MFile::Basename -MFile::Copy \
         -e 'if (m/^(\s*(?:excludesfile|attributesfile|template)\s*=\s*)(\S+)/) {' \
         -e '  my ($prefix, $o) = ($1, $2); ' \
         -e '  my $n = File::Basename::basename($o);' \
         -e '  File::Copy::copy($o, $n) or die "cp $o $n: $!";' \
         -e '  $_ = "$prefix/home/$ENV{USERNAME}/$n\n";' \
         -e '}' $HOME/.gitconfig >.gitconfig
    git config -f .gitconfig user.name "$USER_FULLNAME"
    git config -f .gitconfig user.email "$USER_EMAIL"

    # Set up ox-map-hosts configuration.
    if test -f $HOME/.ox-map-hosts-rc; then
        cp $HOME/.ox-map-hosts-rc .
    fi
)

if ! test -d setup; then
    mkdir setup
fi

tar czf setup/userhome.tar.gz -C $TMPDIR .
rm -rf $TMPDIR
